apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: allow-get
  name: allow-get
  namespace: test-rbac
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: bitnami/kubectl:latest
    name: allow-get
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: allow-get
status: {}
