apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: allow-list
  namespace: test-rbac
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
